FROM python:3

WORKDIR /project
 
COPY scrape-rec/ .
COPY scrapy-statsd/ scrapy-statsd

RUN pip3 install --no-cache-dir -r requirements.txt
RUN pip3 install scrapy-statsd/

CMD [ "python3", "start_crawler.py" ]