version: '3'
services:

  postgres:
    image: postgres
    env_file:
     - ./docker_env.list
    ports:
      - 5435:5432

  scraper:
    image: scraper
    volumes:
      - httpcache:/var/lib/httpcache/ 
    network_mode: host
    entrypoint: python3 start_crawler.py

volumes:
  pgdata:
    external: true
  httpcache:
    external: true
