amenities = ['parking', 'terrace', 'cellar']

keywords = {
    'cluj-napoca': {
        'neighborhoods': [
            'andrei muresanu',
            'bulgaria',
            'buna ziua',
            'centru',
            'dambul rotund',
            'gara',
            'horea',
            'manastur',
            'grigorescu',
            'gruia',
            'iris',
            'intre lacuri',
            'marasti',
            'someseni',
            'zorilor',
            'sopor',
            'faget',
            'borhanci',
            'becas',
            'expo transilvania',
            'iulius',
            'vivo',
            'polus',
            'floresti',
            'viteazu',
            'sigma',
            'piata unirii',
            'dorobantilor',
            'the office',
            'plopilor',
            'calea turzii',
            'baciu',
            'gheorgheni',
            'interservisan',
            'ultracentral',
            'europa',
            'muzeului',
            'calea baciului',
            'titulescu',
            'usamv',
        ],
        'terrace': ['terasa', 'balcon', 'balcoane'],
        'parking': ['parcare', 'garaj'],
        'cellar': ['pivnita', 'boxa'],
    }
}
